apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: varun/authservice
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: authservice
  ports:
    - name: authservice
      protocol: TCP
      port: 4000
      targetPort: 4000
